#' @title Predict Method for fastNaiveBayes fits
#' @description Uses a fastNaiveBayes model and a new data set to create the classifications.
#'     This can either be the raw probabilities generated by the fastNaiveBayes model or the classes themselves.
#'
#' @param object A fitted object of class "fnb.mixed", "fnb.bernoulli", "fnb.gaussian", "fnb.multinomial" or "fnb.train".
#' @param newdata A numeric matrix. A Sparse dgcMatrix is also accepted.
#'     Note: if fnb.naiveBayes was used to create the model, then if newdata contains features that were not encountered in the training data, these are omitted from the prediction.
#'     Furthermore, newdata can contain fewer features than encountered in the training data. In this case, newdata will be padded with
#'     extra columns all filled with 0's.
#' @param type If "raw", the conditional a-posterior probabilities for each class are returned, and the class with maximal probability else.
#' @param sparse Use a sparse matrix? If true a sparse matrix will be constructed from x.
#'     It's possible to directly feed a sparse dgcMatrix as x, which will set this parameter to TRUE
#' @param threshold A threshold for the minimum probability. For Bernoulli and Multinomial event models Laplace smoothing should solve this,
#' but in the case of Gaussian event models, this ensures numerical probabilities.
#' @param ... Not used.
#' @return If type = 'class', a factor with classified class levels. If type = 'raw', a matrix with the predicted probabilities of
#'     each class, where each column in the matrix corresponds to a class level.
#'
#' @export
#' @import Matrix
#'
#' @details In the extremely unlikely case that two classes have the exact same estimated probability, the first encountered class
#'     is used as the classification.
#'
#'     Using a sparse matrix directly can be especially useful if it's necessary to use predict multiple times on the same matrix or
#'     on different subselections of the same initial matrix, see examples for further details.
#' @examples
#' rm(list = ls())
#' library(fastNaiveBayes)
#' cars <- mtcars
#' y <- as.factor(ifelse(cars$mpg > 25, "High", "Low"))
#' x <- cars[, 2:ncol(cars)]
#'
#' dist <- fnb.detect_distribution(x, nrows = nrow(x))
#' print(dist)
#'
#' # Mixed event models
#' mod <- fnb.mixed(x, y, laplace = 1)
#' pred <- predict(mod, newdata = x)
#' mean(pred != y)
#'
#' # Bernoulli only
#' vars <- c(dist$bernoulli, dist$multinomial)
#' newx <- x[, vars]
#' for (i in 1:ncol(newx)) {
#'   newx[[i]] <- as.factor(newx[[i]])
#' }
#' new_mat <- model.matrix(y ~ . - 1, cbind(y, newx))
#'
#' mod <- fnb.bernoulli(new_mat, y, laplace = 1)
#' pred <- predict(mod, newdata = new_mat)
#' mean(pred != y)
#'
#' # Multinomial only
#' vars <- c(dist$bernoulli, dist$multinomial)
#' newx <- x[, vars]
#'
#' mod <- fnb.multinomial(newx, y, laplace = 1)
#' pred <- predict(mod, newdata = newx)
#' mean(pred != y)
#'
#' # Gaussian only
#' vars <- c("hp", dist$gaussian)
#' newx <- x[, vars]
#'
#' mod <- fnb.gaussian(newx, y)
#' pred <- predict(mod, newdata = newx)
#' mean(pred != y)
#'
#' @seealso \code{\link{fastNaiveBayes}} for the fastNaiveBayes model.
#' @rdname predict.fastNaiveBayes
predict.fastNaiveBayes <- function(object, newdata, type = c("class", "raw"),
                                   sparse = FALSE, threshold = .Machine$double.eps, ...){

  type <- match.arg(type)
  if (class(newdata)[1] != "dgCMatrix") {
    if (!is.matrix(newdata)) {
      newdata <- as.matrix(newdata)
    }
    if (sparse) {
      newdata <- Matrix(newdata, sparse = TRUE)
    }
  } else {
    sparse <- TRUE
  }

  names <- object$names
  distribution <- object$distribution

  probs <- NULL
  for (i in 1:length(object$mod$models)) {
    model <- object$mod$models[[i]]
    newnames <- model$names
    newx <- newdata[, model$names]
    if(length(model$names)==1){
      newx <- as.matrix(newx)
      colnames(newx) <- model$names
    }

    if(class(model)=="fnb.gaussian"){
      names <- intersect(model$names, colnames(newx))
      if(length(model$names)!=length(names)){
        warning('Columns in test and train set not equal! Only the intersect of the two is used for prediction')
        newx <- newx[, names]
      }
    }else{
      names <- intersect(model$names, colnames(newx))
      if(length(model$names)!=length(names)){
        warning('Columns in test and train set not equal! Newdata is padded with zeros')
        newx <- newx[, names]

        other_names <- setdiff(model$names, colnames(newx))
        if(length(other_names)>0){
          if (sparse) {
            other_mat <- Matrix(0L, nrow = nrow(newx), ncol = length(other_names), sparse = TRUE)
          } else {
            other_mat <- matrix(0L, nrow = nrow(newx), ncol = length(other_names))
          }
          colnames(other_mat) <- other_names

          newx <- cbind(newx, other_mat)
        }
        newx <- newx[, names]
      }
    }
    if (length(newnames) == 1) {
      newx <- as.matrix(newx)
      colnames(newx) <- newnames
    }

    if (is.null(probs)) {
      probs <- stats::predict(model, newx, type = "rawprob", sparse, threshold)
    } else {
      probs <- probs + stats::predict(model, newx, type = "rawprob", sparse, threshold)
    }
  }
  probs <- exp(probs)

  priors <- object$mod$priors
  for(i in 1:length(priors)){
    probs[,i] <- probs[,i]*priors[i]
  }

  denom <- rowSums(probs)
  denom[denom==0] <- 1
  probs <- probs / denom

  if (type == "class") {
    class <- as.factor(object$levels[max.col(probs, ties.method = "first")])
    levels(class) <- object$levels
    return(class)
  }
  return(probs)
}
